### PR TITLE
Use avr-libc implementation of crc8

### PR DESCRIPTION
**Pull request by tico-tico**
They have a nice implementation of crc8 in assembly language. The result is smaller and (i guess) faster.
They have crc16 as well, but i can't understand what you are doing in the code, so i can't propose any changes for crc16.

### CODE REVIEW

**Comment by orgua** [comment]
I have tested the 16-bit C-implementation from the [website](http://www.atmel.com/webdoc/AVRLibcReferenceManual/group__util__crc_1ga95371c87f25b0a2497d9cba13190847f.html)
- for 254bytes it needs ~1880µs on an atmega328 @16MHz. 
- Then i used the direct fn-call to the lib and it takes 500µs.
- The Crc16 in OW-Lib needs about 1400µs.

**Comment by tico-tico** [comment]
You mean you used asm function `_crc16_update(uint16_t __crc, uint8_t __data) ` and you liked it?

**Comment by orgua** [comment]
indeed, i did. and it returned the right value too. could you imagine?

**Comment by tico-tico** [comment]
> could you imagine?

ah! the magic indeed! https://github.com/PaulStoffregen/OneWire/pull/13

**Pull request merged**
